image: node:8

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn install
    - yarn lint
    - yarn test

build:static_files:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public/
    expire_in: 1 day

deploy:docker_cloud:preview:
  stage: deploy
  image: docker:latest
  script:
    - docker build --tag smrtv/docker-image:ch-smartive-preview .
    - docker login -u $DOCKER_ID_USER -p $DOCKER_ID_PASSWORD
    - docker push smrtv/docker-image:ch-smartive-preview
  only:
    - branches
  except:
    - develop
    - master
  dependencies:
    - build:static_files
  environment:
    name: preview
    url: https://preview.smartive.ch

deploy:docker_cloud:stage:
  stage: deploy
  image: docker:latest
  script:
    - docker build --tag smrtv/docker-image:ch-smartive-stage .
    - docker login -u $DOCKER_ID_USER -p $DOCKER_ID_PASSWORD
    - docker push smrtv/docker-image:ch-smartive-stage
  only:
    - develop
  dependencies:
    - build:static_files
  environment:
    name: stage
    url: https://stage.smartive.ch

deploy:docker_cloud:prod:
  stage: deploy
  image: docker:latest
  script:
    - docker build --tag smrtv/docker-image:ch-smartive-prod .
    - docker login -u $DOCKER_ID_USER -p $DOCKER_ID_PASSWORD
    - docker push smrtv/docker-image:ch-smartive-prod
  only:
    - master
  dependencies:
    - build:static_files
  environment:
    name: prod
    url: https://smartive.ch
