image: node:9

stages:
  - test
  - build
  - deploy docker
  - deploy app

cache:
  paths:
    - node_modules

lint:
  stage: test
  script:
    - yarn install
    - yarn lint

test:
  stage: test
  script:
    - yarn install
    - yarn test

build static files:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public/
    expire_in: 1 day

## Preview

deploy docker preview:
  stage: deploy docker
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build static files
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.smartive.ch
    - docker build -t registry.smartive.ch/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker push registry.smartive.ch/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  except:
    - master

deploy app preview:
  stage: deploy app
  image: registry.smartive.ch/smartive/kubernetes-deploy:CI_COMMIT_REF_SLUG
  variables:
    NAMESPACE: preview
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  script:
    - k8s-prepare
    - rm ./deployment/prod-ingress.yml
    - k8s-apply
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.smartive.ch
    on_stop: stop preview
  except:
    - master

stop preview:
  stage: deploy app
  image: registry.smartive.ch/smartive/kubernetes-deploy:CI_COMMIT_REF_SLUG
  variables:
    NAMESPACE: preview
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  script:
    - k8s-prepare
    - rm ./deployment/prod-ingress.yml
    - kubectl delete -f ./deployment
  when: manual
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    action: stop

## Production

deploy docker production:
  stage: deploy docker
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build static files
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.smartive.ch
    - docker build -t registry.smartive.ch/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest .
    - docker push registry.smartive.ch/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
    - master

deploy app production:
  stage: deploy app
  image: registry.smartive.ch/smartive/kubernetes-deploy:latest
  variables:
    NAMESPACE: default
    IMAGE_TAG: latest
  script:
    - k8s-prepare
    - rm ./deployment/preview-ingress.yml
    - k8s-apply
  environment:
    name: production
    url: https://smartive.ch
  only:
    - master
