include:
  - 'https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml'

stages:
  - build
  - deploy

build:
  extends: .gcb-docker
  stage: build
  variables:
    SUB_REGISTRY: $REGISTRY
    SUB_CI_PROJECT_NAMESPACE: $CI_PROJECT_NAMESPACE
    SUB_CI_PROJECT_NAME: $CI_PROJECT_NAME
    SUB_TAG: $CI_COMMIT_REF_SLUG

deploy preview:
  extends: .k8s-deploy
  stage: deploy
  variables:
    APP_NAME: $CI_COMMIT_REF_SLUG
    CERT_ISSUER: letsencrypt-staging
    KUBE_CONFIG: $DEV_KUBE_CONFIG
    REPLICAS: '1'
    TAG: $CI_COMMIT_REF_SLUG
    URL: $CI_COMMIT_REF_SLUG-gatsby.smartive.ch
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-gatsby.smartive.ch
    on_stop: stop preview
  except:
    - master

stop preview:
  extends: .k8s-delete
  stage: deploy
  image: node:10
  variables:
    APP_NAME: $CI_COMMIT_REF_SLUG
    CERT_ISSUER: letsencrypt-staging
    GIT_CHECKOUT: 'false'
    KUBE_CONFIG: $DEV_KUBE_CONFIG
    REPLICAS: '1'
    TAG: $CI_COMMIT_REF_SLUG
    URL: $CI_COMMIT_REF_SLUG-gatsby.smartive.ch
  when: manual
  before_script:
    - npm i -g @smartive/kuby
    - git checkout $CI_COMMIT_SHA || git checkout master
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    action: stop
  except:
    - master

deploy prod:
  extends: .k8s-deploy
  stage: deploy
  variables:
    APP_NAME: $CI_PROJECT_NAME
    CERT_ISSUER: letsencrypt-production
    KUBE_CONFIG: $PROD_KUBE_CONFIG
    REPLICAS: '2'
    TAG: $CI_COMMIT_REF_SLUG
    URL: smartive.ch
  environment:
    name: production
    url: https://smartive.ch
  only:
    - master
