variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build
  - deploy

build:static_files:
  stage: build
  image: node:8
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public/
    expire_in: 1 day

deploy:docker_cloud:
  stage: deploy
  image: docker:latest
  script:
    - docker build --tag smrtv/docker-image:ch-smartive-stage .
    - docker login -u $DOCKER_ID_USER -p $DOCKER_ID_PASSWORD
    - docker push smrtv/docker-image:ch-smartive-stage
  only:
    - master
  dependencies:
    - build:static_files
