apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
  namespace: ${NAMESPACE}
  labels:
    app: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
    namespace: ${NAMESPACE}
spec:
  replicas: ${NUMBER_OF_REPLICAS}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
      name: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
      namespace: ${NAMESPACE}
  template:
    metadata:
      labels:
        app: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
        name: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}
        namespace: ${NAMESPACE}
    spec:
      containers:
      - name: app
        image: registry.smartive.ch/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG}
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        env:
        - name: COMMIT_HASH
          value: ${CI_COMMIT_SHA}

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
